name: Production Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      deployments: write
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cloudflare-build
          path: ./
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Wrangler
        run: npm install --no-save wrangler@$(node -p "require('./package.json').devDependencies.wrangler || require('./package.json').dependencies.wrangler")

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: production
